#pragma once

#ifndef _ISO14229_H
#define _ISO14229_H

#define UDS_SERVICE_DSC     0x10
#define UDS_SERVICE_ER      0x11
#define UDS_SERVICE_CDTCI   0x14
#define UDS_SERVICE_RDTCI   0x19
#define UDS_SERVICE_RDBI    0x22
#define UDS_SERVICE_RMBA    0x23
#define UDS_SERVICE_RSDBI   0x24
#define UDS_SERVICE_SA      0x27
#define UDS_SERVICE_CC      0x28
#define UDS_SERVICE_RDBPI   0x2A
#define UDS_SERVICE_DDDI    0x2C
#define UDS_SERVICE_WDBI    0x2E
#define UDS_SERVICE_IOCBI   0x2F
#define UDS_SERVICE_RC      0x31
#define UDS_SERVICE_RD      0x34
#define UDS_SERVICE_RU      0x35
#define UDS_SERVICE_TD      0x36
#define UDS_SERVICE_RTE     0x37
#define UDS_SERVICE_RFT     0x38
#define UDS_SERVICE_WMBA    0x3D
#define UDS_SERVICE_TP      0x3E
#define UDS_SERVICE_ERR     0x3F

#define UDS_RESPONSE_GR       0x10
#define UDS_RESPONSE_SNS      0x11
#define UDS_RESPONSE_SFNS     0x12
#define UDS_RESPONSE_IMLOIF   0x13
#define UDS_RESPONSE_RTL      0x14
#define UDS_RESPONSE_BRR      0x21
#define UDS_RESPONSE_CNC      0x22
#define UDS_RESPONSE_RSE      0x24
#define UDS_RESPONSE_NRFSC    0x25
#define UDS_RESPONSE_FPEORA   0x26
#define UDS_RESPONSE_ROOR     0x31
#define UDS_RESPONSE_SAD      0x33
#define UDS_RESPONSE_IK       0x35
#define UDS_RESPONSE_ENOA     0x36
#define UDS_RESPONSE_RTDNE    0x37
#define UDS_RESPONSE_UDNA     0x70
#define UDS_RESPONSE_TDS      0x71
#define UDS_RESPONSE_GPF      0x72
#define UDS_RESPONSE_WBSC     0x73
#define UDS_RESPONSE_RCRRP    0x78
#define UDS_RESPONSE_SFNSIAS  0x7E
#define UDS_RESPONSE_SNSIAS   0x7F

#define UDS_SID_MASK    0xBF
#define UDS_REPLY_MASK  0x40
#define UDS_SID_OFFSET  0
#define UDS_SID_LEN     1
#define UDS_DATA_OFFSET 1

#define UDS_DSC_SESSION_TYPE_OFFSET             (UDS_DATA_OFFSET + 0)
#define UDS_DSC_SESSION_TYPE_LEN                1
#define UDS_DSC_SESSION_PARAMETER_RECORD_OFFSET (UDS_DSC_SESSION_TYPE_OFFSET + UDS_DSC_SESSION_TYPE_LEN)

#define UDS_DSC_SESSION_TYPES_DEFAULT     1
#define UDS_DSC_SESSION_TYPES_PROGRAMMING 2
#define UDS_DSC_SESSION_TYPES_EXTENDED    3

#define UDS_RDTCI_REPORT_TYPE_OFFSET (UDS_DATA_OFFSET + 0)
#define UDS_RDTCI_REPORT_TYPE_LEN    1
#define UDS_RDTCI_RECORD_OFFSET      (UDS_RDTCI_REPORT_TYPE_OFFSET + UDS_RDTCI_REPORT_TYPE_LEN)

#define UDS_RDTCI_REPORT_TYPES_NUMBER_BY_STATUS_MASK 0x1
#define UDS_RDTCI_REPORT_TYPES_BY_STATUS_MASK 0x2
#define UDS_RDTCI_REPORT_TYPES_SNAPSHOT_IDENTIFICATION 0x3
#define UDS_RDTCI_REPORT_TYPES_SNAPSHOT_RECORD_BY_DTC 0x4
#define UDS_RDTCI_REPORT_TYPES_SNAPSHOT_RECORD_BY_RECORD 0x5
#define UDS_RDTCI_REPORT_TYPES_EXTENDED_RECARD_BY_DTC 0x6
#define UDS_RDTCI_REPORT_TYPES_SUPPORTED_DTC 0xA

#define UDS_RDBI_DATA_IDENTIFIER_OFFSET (UDS_DATA_OFFSET + 0)
#define UDS_RDBI_DATA_IDENTIFIER_LEN    2
#define UDS_RDBI_DATA_RECORD_OFFSET     (UDS_RDBI_DATA_IDENTIFIER_OFFSET + UDS_RDBI_DATA_IDENTIFIER_LEN)

#define UDS_SA_TYPE_OFFSET (UDS_DATA_OFFSET + 0)
#define UDS_SA_TYPE_LEN    1
#define UDS_SA_KEY_OFFSET  (UDS_SA_TYPE_OFFSET + UDS_SA_TYPE_LEN)
#define UDS_SA_SEED_OFFSET (UDS_SA_TYPE_OFFSET + UDS_SA_TYPE_LEN)

#define UDS_SA_TYPES_SEED   1
#define UDS_SA_TYPES_KEY    2
#define UDS_SA_TYPES_SEED_2 3
#define UDS_SA_TYPES_KEY_2  4

#define UDS_WDBI_DATA_IDENTIFIER_OFFSET (UDS_DATA_OFFSET + 0)
#define UDS_WDBI_DATA_IDENTIFIER_LEN    2
#define UDS_WDBI_DATA_RECORD_OFFSET     (UDS_WDBI_DATA_IDENTIFIER_OFFSET + UDS_WDBI_DATA_IDENTIFIER_LEN)

#define UDS_ERR_SID_OFFSET   (UDS_DATA_OFFSET + 0)
#define UDS_ERR_SID_LEN      1
#define UDS_ERR_CODE_OFFSET  (UDS_ERR_SID_OFFSET + UDS_ERR_SID_LEN)
#define UDS_ERR_CODE_LEN     1

#endif /* _ISO14229_H */