INCLUDE("${CMAKE_CURRENT_LIST_DIR}/UDSTargets.cmake")

# Compute the installation prefix relative to this file.
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

SET(UDS_SWIG_DIRECTORY "${_IMPORT_PREFIX}/lib/swig/UDS")

# Cleanup temporary variables.
SET(_IMPORT_PREFIX)